# Generated by Django 2.2.5 on 2019-12-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('1', 'Web Design'), ('2', 'JavaScript'), ('3', 'CSS'), ('4', 'Jquery')], max_length=2),
        ),
    ]
